# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "iojs"
  - "7"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -U postgres
script: ./go test
